# Generated by Django 5.0.7 on 2024-07-30 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projecttask',
            old_name='description',
            new_name='сomment',
        ),
    ]
